### ISSUE TITLE
[net-misc/syncthing] go build failing

### ISSUE THREAD

**Issue by skruppy** [Dr-Terrible/go-overlay#10]
When emerging syncthing, the build fails. I can't find any clue why. The error message is:

```
[...]
github.com/syncthing/syncthing/lib/model
github.com/syncthing/syncthing/lib/connections
github.com/syncthing/syncthing/cmd/syncthing
# github.com/syncthing/syncthing/cmd/syncthing
usage: 6l [options] main.6
  -1    use alternate profiling code
  -8    assume 64-bit addresses
  -B info
        define ELF NT_GNU_BUILD_ID note
  -C    check Go calls to C code
  -D addr
        data address
  -E sym
        entry symbol
  -I interp
        set ELF interp
  -L dir
        add dir to library path
  -H head
        header type
  -K    add stack underflow checks
  -O    print pc-line tables
  -Q    debug byte-register code gen
  -R rnd
        address rounding
  -S    check type signatures
  -T addr
        text address
  -V    print version and exit
  -W    disassemble input
  -X name value
        define string data
  -Z    clear stack frame on entry
  -a    disassemble output
  -c    dump call graph
  -d    disable dynamic executable
  -extld ld
        linker to run in external mode
  -extldflags ldflags
        flags for external linker
  -f    ignore version mismatch
  -g    disable go package data checks
  -installsuffix suffix
        pkg directory suffix
  -k sym
        set field tracking symbol
  -linkmode mode
        set link mode (internal, external, auto)
  -n    dump symbol table
  -o outfile
        set output file
  -r dir1:dir2:...
        set ELF dynamic linker search path
  -race
        enable race detector
  -s    disable symbol table
  -shared
        generate shared object (implies -linkmode external)
  -tmpdir dir
        leave temporary files in this directory
  -u    reject unsafe packages
  -v    print link trace
  -w    disable DWARF generation
 * ERROR: net-misc/syncthing-0.12.11::go-overlay failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_compile
 *   environment, line 2519:  Called golang-single_src_compile
 *   environment, line 1458:  Called golang-single_do_build_ '-v' '-p' '5' '-a' '-o' '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gobin/syncthing' 'github.com/syncthing/syncthing/cmd/syncthing'
 *   environment, line 1428:  Called die
 * The specific snippet of code:
 *       ${EGO} build -ldflags "${GOLANG_PKG_LDFLAGS}" -tags "${GOLANG_PKG_TAGS}" $* || die
 * 
 * If you need support, post the output of `emerge --info '=net-misc/syncthing-0.12.11::go-overlay'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/syncthing-0.12.11::go-overlay'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/syncthing-0.12.11/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/syncthing-0.12.11/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing'
 * S: '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing'
```

How can I help to fix this?

**Comment by Dr-Terrible** [comment]
Thank you for the report @Skrupellos.

Unfortunately, I wasn't able to reproduce this issue (Syncthing v0.12.11 compiles and installs correctly on my testing machines); to properly find the culprit I need a copy of  `/var/tmp/portage/net-misc/syncthing-0.12.11/temp/build.log`, and the output of both `emerge --info '=net-misc/syncthing-0.12.11::go-overlay'` and `emerge -pqv '=dev-lang/go'`.

**Comment by skruppy** [comment]
On 2016-01-08 09:59, Mauro Toffanin wrote:

> Unfortunately, I wasn't able to reproduce this issues (Syncthing v0.12.11 compiles and installs correctly on my testing machines); to properly find the curlprit I need a copy of  `/var/tmp/portage/net-misc/syncthing-0.12.11/temp/build.log`, and finally the output of both `emerge --info '=net-misc/syncthing-0.12.11::go-overlay'` and `emerge -pqv '=net-misc/syncthing-0.12.11::go-overlay'`.
> here they are :)

# Portage 2.2.26 (python 3.4.3-final-0, hardened/linux/amd64, gcc-4.9.3, glibc-2.21-r1, 4.1.7-hardened-r1 x86_64)

```
                     System Settings
```

# 

System uname: Linux-4.1.7-hardened-r1-x86_64-Intel-R-_Core-TM-_i5-4200U_CPU_@_1.60GHz-with-gentoo-2.2
KiB Mem:     8096436 total,   6083876 free
KiB Swap:    4194300 total,   4194300 free
Timestamp of repository gentoo: Thu, 07 Jan 2016 19:30:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.18.4::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

skruppy
    location: /usr/local/portage
    masters: gentoo

dlang
    location: /var/lib/layman/dlang
    sync-type: laymansync
    sync-uri: https://github.com/gentoo/dlang.git
    masters: gentoo
    priority: 50

go-overlay
    location: /var/lib/layman/go-overlay
    sync-type: laymansync
    sync-uri: https://github.com/Dr-Terrible/go-overlay.git
    masters: gentoo
    priority: 50

haskell
    location: /var/lib/layman/haskell
    sync-type: laymansync
    sync-uri: git://github.com/gentoo-haskell/gentoo-haskell.git
    masters: gentoo
    priority: 50

palemoon
    location: /var/lib/layman/palemoon
    sync-type: laymansync
    sync-uri: https://github.com/deuiore/palemoon-overlay.git
    masters: gentoo
    priority: 50

torbrowser
    location: /var/lib/layman/torbrowser
    sync-type: laymansync
    sync-uri: https://github.com/MeisterP/torbrowser-overlay.git
    masters: gentoo
    priority: 50

zetok-overlay
    location: /var/lib/layman/zetok-overlay
    sync-type: laymansync
    sync-uri: https://gitlab.com/zetok/zetok-overlay.git
    masters: gentoo
    priority: 50

local-crossdev
    location: /usr/local/portage-crossdev
    masters: gentoo
    priority: 9999

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="\* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/bin/cusdm /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.5/ext-active/ /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.5/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.5/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="ftp://gentoo.imj.fr/pub/gentoo/ ftp://sunsite.informatik.rwth-aachen.de/pub/Linux/gentoo http://gd.tuwien.ac.at/opsys/linux/gentoo/ rsync://mirror.netcologne.de/gentoo/"
LANG="de_DE.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl aes amd64 amr apng atmo avx avx2 berkdb bidi bluray bzip2 cdda clang cli cpudetection cracklib crypt cups cxx dbus dri exif flac fma3 fontconfig gdbm gif git gnutls gpm gtk gtk3 gudev hardened hscolour iconv icu idn ipv6 jpeg jpeg2k justify kerberos libnotify libproxy libsamplerate lirc minizip mmx mmxext modules mp3 multilib ncurses networkmanager nls nptl offensive ogg opencl opengl openmp opus pam pax_kernel pcre pie png popcnt portaudio pulseaudio python rar readline rtmp schroedinger seccomp session speex sqlite sse sse2 sse3 sse4_1 sse4_2 ssl ssp ssse3 subversion svg systemd tcpd theora threads tiff truetype twolame udev unicode upnp urandom v4l vaapi vcdx vorbis vpx wavpack wayland x264 xattr xetex xinerama xml xtpax xvid zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64 pc" INPUT_DEVICES="evdev synaptics" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en de" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

[ebuild  N    ] net-misc/syncthing-0.12.11  USE="cli inotify -doc {-test}" 

[32;01m \* [39;49;00mPackage:    net-misc/syncthing-0.12.11
[32;01m \* [39;49;00mRepository: go-overlay
[32;01m \* [39;49;00mMaintainer: toffanin.mauro@gmail.com
[32;01m \* [39;49;00mUpstream:   https://github.com/syncthing/syncthing/issues
[32;01m \* [39;49;00mUSE:        abi_x86_64 amd64 cli elibc_glibc inotify kernel_linux userland_GNU
[32;01m \* [39;49;00mFEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox

> > > Unpacking source...
> > > Unpacking syncthing-0.12.11.tar.gz to /var/tmp/portage/net-misc/syncthing-0.12.11/work
> > > Source unpacked in /var/tmp/portage/net-misc/syncthing-0.12.11/work
> > > /var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing /var/tmp/portage/net-misc/syncthing-0.12.11/work
> > > /var/tmp/portage/net-misc/syncthing-0.12.11/work
> > > Preparing source in /var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing ...
> > >  [32;01m_[0m Found GoLang version: 1.4.2
> > >  [32;01m_[0m Setting up GoLang build environment ...
> > > [A[309C [34;01m[ [32;01mok[34;01m ][0m
> > >  [32;01m_[0m Preparing GoLang build environment in /var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src
> > > Source prepared.
> > > Configuring source in /var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing ...
> > >  [32;01m_[0m  go env
> > >  [32;01m_[0m  - GOARCH="amd64"
> > >  [32;01m_[0m  - GOBIN="/var/tmp/portage/net-misc/syncthing-0.12.11/work/gobin"
> > >  [32;01m_[0m  - GOCHAR="6"
> > >  [32;01m_[0m  - GOEXE=""
> > >  [32;01m_[0m  - GOHOSTARCH="amd64"
> > >  [32;01m_[0m  - GOHOSTOS="linux"
> > >  [32;01m_[0m  - GOOS="linux"
> > >  [32;01m_[0m  - GOPATH="/var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath"
> > >  [32;01m_[0m  - GORACE=""
> > >  [32;01m_[0m  - GOROOT="/usr/lib/go"
> > >  [32;01m_[0m  - GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
> > >  [32;01m_[0m  - CC="x86_64-pc-linux-gnu-gcc"
> > >  [32;01m_[0m  - GOGCCFLAGS="-fPIC -m64 -fmessage-length=0"
> > >  [32;01m_[0m  - CXX="g++"
> > >  [32;01m_[0m  - CGO_ENABLED="0"
> > >  [32;01m_[0m go clean -i -v github.com/syncthing/syncthing/cmd/syncthing
> > >  [32;01m_[0m go generate -v ./...
> > > cmd/stcompdirs/main.go
> > > cmd/stevents/main.go
> > > cmd/stfileinfo/main.go
> > > cmd/stfinddevice/main.go
> > > cmd/stindex/dump.go
> > > cmd/stindex/dumpsize.go
> > > cmd/stindex/main.go
> > > cmd/stindex/util.go
> > > cmd/stsigtool/main.go
> > > cmd/stwatchfile/main.go
> > > cmd/syncthing/addresslister.go
> > > cmd/syncthing/auditservice.go
> > > cmd/syncthing/auditservice_test.go
> > > cmd/syncthing/blockprof.go
> > > cmd/syncthing/debug.go
> > > cmd/syncthing/gui.go
> > > cmd/syncthing/gui_auth.go
> > > cmd/syncthing/gui_csrf.go
> > > cmd/syncthing/gui_unix.go
> > > cmd/syncthing/heapprof.go
> > > cmd/syncthing/locations.go
> > > cmd/syncthing/main.go
> > > cmd/syncthing/main_test.go
> > > cmd/syncthing/memsize_linux.go
> > > cmd/syncthing/monitor.go
> > > cmd/syncthing/openurl_unix.go
> > > cmd/syncthing/perfstats_unix.go
> > > cmd/syncthing/random.go
> > > cmd/syncthing/random_test.go
> > > cmd/syncthing/summaryservice.go
> > > cmd/syncthing/upnpservice.go
> > > cmd/syncthing/usage.go
> > > cmd/syncthing/usage_report.go
> > > cmd/syncthing/verboseservice.go
> > > lib/auto/auto_test.go
> > > lib/auto/doc.go
> > > lib/auto/gui.files.go
> > > lib/beacon/beacon.go
> > > lib/beacon/broadcast.go
> > > lib/beacon/broadcast_test.go
> > > lib/beacon/debug.go
> > > lib/beacon/doc.go
> > > lib/beacon/multicast.go
> > > lib/config/commit_test.go
> > > lib/config/config.go
> > > lib/config/config_test.go
> > > lib/config/debug.go
> > > lib/config/deviceconfiguration.go
> > > lib/config/folderconfiguration.go
> > > lib/config/guiconfiguration.go
> > > lib/config/optionsconfiguration.go
> > > lib/config/pullorder.go
> > > lib/config/versioningconfiguration.go
> > > lib/config/wrapper.go
> > > lib/connections/connections.go
> > > lib/connections/connections_tcp.go
> > > lib/connections/debug.go
> > > lib/connections/limitedreader.go
> > > lib/connections/limitedwriter.go
> > > lib/db/blockmap.go
> > > lib/db/blockmap_test.go
> > > lib/db/debug.go
> > > lib/db/leveldb.go
> > > lib/db/leveldb_dbinstance.go
> > > lib/db/leveldb_test.go
> > > lib/db/leveldb_transactions.go
> > > lib/db/leveldb_xdr.go
> > > lib/db/namespaced.go
> > > lib/db/namespaced_test.go
> > > lib/db/set.go
> > > lib/db/set_test.go
> > > lib/db/truncated.go
> > > lib/db/virtualmtime.go
> > > lib/db/virtualmtime_test.go
> > > lib/dialer/internal.go
> > > lib/dialer/public.go
> > > lib/discover/cache.go
> > > lib/discover/cache_test.go
> > > lib/discover/debug.go
> > > lib/discover/discover.go
> > > lib/discover/doc.go
> > > lib/discover/global.go
> > > lib/discover/global_test.go
> > > lib/discover/local.go
> > > lib/discover/localpackets.go
> > > lib/discover/localpackets_xdr.go
> > > lib/events/debug.go
> > > lib/events/events.go
> > > lib/events/events_test.go
> > > lib/fnmatch/fnmatch.go
> > > lib/fnmatch/fnmatch_test.go
> > > lib/ignore/cache.go
> > > lib/ignore/cache_test.go
> > > lib/ignore/ignore.go
> > > lib/ignore/ignore_test.go
> > > lib/logger/logger.go
> > > lib/logger/logger_test.go
> > > lib/model/connection.go
> > > lib/model/debug.go
> > > lib/model/deviceactivity.go
> > > lib/model/deviceactivity_test.go
> > > lib/model/doc.go
> > > lib/model/folderstate.go
> > > lib/model/model.go
> > > lib/model/model_test.go
> > > lib/model/progressemitter.go
> > > lib/model/progressemitter_test.go
> > > lib/model/queue.go
> > > lib/model/queue_test.go
> > > lib/model/rofolder.go
> > > lib/model/rwfolder.go
> > > lib/model/rwfolder_test.go
> > > lib/model/sharedpullerstate.go
> > > lib/model/sharedpullerstate_test.go
> > > lib/model/tempname.go
> > > lib/model/tempname_test.go
> > > lib/model/util.go
> > > lib/osutil/atomic.go
> > > lib/osutil/atomic_test.go
> > > lib/osutil/filenames_unix.go
> > > lib/osutil/glob_unix.go
> > > lib/osutil/hidden_unix.go
> > > lib/osutil/lan.go
> > > lib/osutil/lstat_broken.go
> > > lib/osutil/mkdirall.go
> > > lib/osutil/osutil.go
> > > lib/osutil/osutil_test.go
> > > lib/osutil/ping.go
> > > lib/osutil/replacingwriter.go
> > > lib/osutil/replacingwriter_test.go
> > > lib/osutil/rlimit_unix.go
> > > lib/protocol/common_test.go
> > > lib/protocol/compression.go
> > > lib/protocol/compression_test.go
> > > lib/protocol/conflict_test.go
> > > lib/protocol/counting.go
> > > lib/protocol/debug.go
> > > lib/protocol/deviceid.go
> > > lib/protocol/deviceid_test.go
> > > lib/protocol/doc.go
> > > lib/protocol/errors.go
> > > lib/protocol/hashalgorithm.go
> > > lib/protocol/hashalgorithm_test.go
> > > lib/protocol/header.go
> > > lib/protocol/message.go
> > > lib/protocol/message_xdr.go
> > > lib/protocol/nativemodel_unix.go
> > > lib/protocol/protocol.go
> > > lib/protocol/protocol_test.go
> > > lib/protocol/vector.go
> > > lib/protocol/vector_compare.go
> > > lib/protocol/vector_compare_test.go
> > > lib/protocol/vector_test.go
> > > lib/protocol/vector_xdr.go
> > > lib/protocol/wireformat.go
> > > lib/rc/debug.go
> > > lib/rc/rc.go
> > > lib/relay/debug.go
> > > lib/relay/relay.go
> > > lib/relay/client/client.go
> > > lib/relay/client/debug.go
> > > lib/relay/client/dynamic.go
> > > lib/relay/client/methods.go
> > > lib/relay/client/static.go
> > > lib/relay/protocol/packets.go
> > > lib/relay/protocol/packets_xdr.go
> > > lib/relay/protocol/protocol.go
> > > lib/scanner/blockqueue.go
> > > lib/scanner/blocks.go
> > > lib/scanner/blocks_test.go
> > > lib/scanner/debug.go
> > > lib/scanner/doc.go
> > > lib/scanner/walk.go
> > > lib/scanner/walk_test.go
> > > lib/signature/signature.go
> > > lib/signature/signature_test.go
> > > lib/stats/debug.go
> > > lib/stats/device.go
> > > lib/stats/folder.go
> > > lib/symlinks/symlink_unix.go
> > > lib/symlinks/targets.go
> > > lib/sync/debug.go
> > > lib/sync/sync.go
> > > lib/sync/sync_test.go
> > > lib/tlsutil/tlsutil.go
> > > lib/upgrade/debug.go
> > > lib/upgrade/signingkey.go
> > > lib/upgrade/upgrade_common.go
> > > lib/upgrade/upgrade_supported.go
> > > lib/upgrade/upgrade_test.go
> > > lib/upnp/debug.go
> > > lib/upnp/upnp.go
> > > lib/upnp/upnp_test.go
> > > lib/versioner/debug.go
> > > lib/versioner/external.go
> > > lib/versioner/simple.go
> > > lib/versioner/staggered.go
> > > lib/versioner/staggered_test.go
> > > lib/versioner/trashcan.go
> > > lib/versioner/trashcan_test.go
> > > lib/versioner/util.go
> > > lib/versioner/versioner.go
> > > lib/versioner/versioner_test.go
> > > Source configured.
> > > Compiling source in /var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing ...
> > >  [32;01m_[0m Using bundled packages from:
> > >  [32;01m_[0m - gopath/src/github.com/syncthing/syncthing/Godeps/_workspace ...
> > > [A[309C [34;01m[ [32;01mok[34;01m ][0m
> > >  [32;01m_[0m go build -ldflags '-X main.Version=v0.12.11 -X main.BuildUser=portage -X main.BuildHost=gentoo' -tags 'noupgrade' -v -p 5 -a -o /var/tmp/portage/net-misc/syncthing-0.12.11/work/gobin/syncthing github.com/syncthing/syncthing/cmd/syncthing
> > > github.com/rcrowley/go-metrics
> > > github.com/syncthing/syncthing/lib/auto
> > > github.com/syncthing/syncthing/lib/logger
> > > github.com/calmh/du
> > > golang.org/x/text/transform
> > > github.com/bkaradzic/go-lz4
> > > github.com/syncthing/syncthing/lib/sync
> > > golang.org/x/text/unicode/norm
> > > github.com/calmh/luhn
> > > github.com/syncthing/syncthing/lib/events
> > > github.com/calmh/xdr
> > > github.com/juju/ratelimit
> > > golang.org/x/net/proxy
> > > github.com/thejerf/suture
> > > golang.org/x/net/internal/iana
> > > golang.org/x/net/ipv6
> > > github.com/syndtr/goleveldb/leveldb/util
> > > github.com/syndtr/goleveldb/leveldb/comparer
> > > github.com/golang/snappy
> > > github.com/syncthing/syncthing/lib/fnmatch
> > > github.com/syncthing/syncthing/lib/ignore
> > > github.com/syndtr/goleveldb/leveldb/cache
> > > github.com/syndtr/goleveldb/leveldb/storage
> > > github.com/syndtr/goleveldb/leveldb/filter
> > > github.com/syndtr/goleveldb/leveldb/opt
> > > github.com/syncthing/syncthing/lib/osutil
> > > github.com/syncthing/syncthing/lib/protocol
> > > github.com/syncthing/syncthing/lib/beacon
> > > github.com/syncthing/syncthing/lib/dialer
> > > github.com/syndtr/goleveldb/leveldb/errors
> > > github.com/syncthing/syncthing/lib/symlinks
> > > github.com/syndtr/goleveldb/leveldb/iterator
> > > github.com/syndtr/goleveldb/leveldb/journal
> > > github.com/syndtr/goleveldb/leveldb/memdb
> > > github.com/syndtr/goleveldb/leveldb/table
> > > github.com/syncthing/syncthing/lib/versioner
> > > github.com/syncthing/syncthing/lib/tlsutil
> > > github.com/kardianos/osext
> > > github.com/syncthing/syncthing/lib/upgrade
> > > github.com/syncthing/syncthing/lib/upnp
> > > github.com/vitrun/qart/gf256
> > > golang.org/x/crypto/blowfish
> > > github.com/vitrun/qart/coding
> > > github.com/syndtr/goleveldb/leveldb
> > > golang.org/x/crypto/bcrypt
> > > github.com/syncthing/syncthing/lib/config
> > > github.com/syncthing/syncthing/lib/discover
> > > github.com/syncthing/syncthing/lib/relay/protocol
> > > github.com/vitrun/qart/qr
> > > github.com/syncthing/syncthing/lib/relay/client
> > > github.com/syncthing/syncthing/lib/relay
> > > github.com/syncthing/syncthing/lib/db
> > > github.com/syncthing/syncthing/lib/scanner
> > > github.com/syncthing/syncthing/lib/stats
> > > github.com/syncthing/syncthing/lib/model
> > > github.com/syncthing/syncthing/lib/connections
> > > github.com/syncthing/syncthing/cmd/syncthing
> > > 
> > > # github.com/syncthing/syncthing/cmd/syncthing
> > > 
> > > usage: 6l [options] main.6
> > >   -1    use alternate profiling code
> > >   -8    assume 64-bit addresses
> > >   -B info
> > >         define ELF NT_GNU_BUILD_ID note
> > >   -C    check Go calls to C code
> > >   -D addr
> > >         data address
> > >   -E sym
> > >         entry symbol
> > >   -I interp
> > >         set ELF interp
> > >   -L dir
> > >         add dir to library path
> > >   -H head
> > >         header type
> > >   -K    add stack underflow checks
> > >   -O    print pc-line tables
> > >   -Q    debug byte-register code gen
> > >   -R rnd
> > >         address rounding
> > >   -S    check type signatures
> > >   -T addr
> > >         text address
> > >   -V    print version and exit
> > >   -W    disassemble input
> > >   -X name value
> > >         define string data
> > >   -Z    clear stack frame on entry
> > >   -a    disassemble output
> > >   -c    dump call graph
> > >   -d    disable dynamic executable
> > >   -extld ld
> > >         linker to run in external mode
> > >   -extldflags ldflags
> > >         flags for external linker
> > >   -f    ignore version mismatch
> > >   -g    disable go package data checks
> > >   -installsuffix suffix
> > >         pkg directory suffix
> > >   -k sym
> > >         set field tracking symbol
> > >   -linkmode mode
> > >         set link mode (internal, external, auto)
> > >   -n    dump symbol table
> > >   -o outfile
> > >         set output file
> > >   -r dir1:dir2:...
> > >         set ELF dynamic linker search path
> > >   -race
> > >         enable race detector
> > >   -s    disable symbol table
> > >   -shared
> > >         generate shared object (implies -linkmode external)
> > >   -tmpdir dir
> > >         leave temporary files in this directory
> > >   -u    reject unsafe packages
> > >   -v    print link trace
> > >   -w    disable DWARF generation
> > >  [31;01m_[0m ERROR: net-misc/syncthing-0.12.11::go-overlay failed (compile phase):
> > >  [31;01m_[0m   (no error message)
> > >  [31;01m_[0m 
> > >  [31;01m_[0m Call stack:
> > >  [31;01m_[0m     ebuild.sh, line  133:  Called src_compile
> > >  [31;01m_[0m   environment, line 2519:  Called golang-single_src_compile
> > >  [31;01m_[0m   environment, line 1458:  Called golang-single_do_build_ '-v' '-p' '5' '-a' '-o' '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gobin/syncthing' 'github.com/syncthing/syncthing/cmd/syncthing'
> > >  [31;01m_[0m   environment, line 1428:  Called die
> > >  [31;01m_[0m The specific snippet of code:
> > >  [31;01m_[0m       ${EGO} build -ldflags "${GOLANG_PKG_LDFLAGS}" -tags "${GOLANG_PKG_TAGS}" $\* || die
> > >  [31;01m_[0m 
> > >  [31;01m_[0m If you need support, post the output of `emerge --info '=net-misc/syncthing-0.12.11::go-overlay'`,
> > >  [31;01m_[0m the complete build log and the output of `emerge -pqv '=net-misc/syncthing-0.12.11::go-overlay'`.
> > >  [31;01m_[0m The complete build log is located at '/var/tmp/portage/net-misc/syncthing-0.12.11/temp/build.log'.
> > >  [31;01m_[0m The ebuild environment file is located at '/var/tmp/portage/net-misc/syncthing-0.12.11/temp/environment'.
> > >  [31;01m_[0m Working directory: '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing'
> > >  [31;01m*[0m S: '/var/tmp/portage/net-misc/syncthing-0.12.11/work/gopath/src/github.com/syncthing/syncthing'

**Comment by Dr-Terrible** [comment]
Thank you for the feedback, @Skrupellos.

Now I'm able to reproduce the compilation failure, and a proper _eclass_ fix is ready to be rolled. A new overlay commit will be made in the next few hours, as soon as all the packages have been re-tested for consistency.

**Comment by Dr-Terrible** [comment]
Commit c15c373 should have fixed the issue. Let me know if there are other problems with Syncthing ebuilds.

p.s.: if you use other golang tools that aren't available from Portage, or from this overlay, feel free to submit a request; I'll be glade to create a proper ebuild.

**Comment by skruppy** [comment]
Works like a charm! Thanks.

**Comment by Dr-Terrible** [comment]
@Skrupellos You're welcome.
