### ISSUE TITLE
[dev-vcs/hub] v2.2.3

### ISSUE THREAD

**Issue by Dr-Terrible** [Dr-Terrible/go-overlay#28]
I have pushed some enhancements for `dev-vcs/hub` with commit 67c3256, but I need feedbacks from people using this tool. Is `hub` working correctly? Is there something missing?

Any kind of feedback is welcome.

cc: @ganto if I remember [correctly](https://github.com/ganto/go-overlay/commit/ffd63078fe233220caf1eb80d7e5c3300ac708cc), you're using hub, right?

**Comment by ganto** [comment]
yes, I started using it a few weeks ago. not yet fully adapted my work flow though. just updated to `hub-2.2.3_pre20160119` and will let you know once I find something

**Comment by Dr-Terrible** [comment]
Hub v2.2.3 has been tagged by upstream a few minutes ago. Right now, I'm working on a new ebuild.
