### ISSUE TITLE
[www-apps/gogs] build failing 

### ISSUE THREAD

**Issue by stikonas** [Dr-Terrible/go-overlay#31]
I tried to compile gogs on both amd64 and arm machines but it didn't compile:
build.log has only this error:

modules/setting/setting.go:257: undefined: bindata.MustAsset

**Comment by stikonas** [comment]
Full build.log: https://stikonas.eu/files/build.log

**Comment by stikonas** [comment]
seems like dependency specification is incomplete:
gogs should depend on >= dev-go/go-bindata-3.0.8_pre2015102

**Comment by Dr-Terrible** [comment]
Thank you for the report, @stikonas.

You're right. I can reproduce the build failure for both the versions of Gogs. With commit 93daf63 I should have fixed the compilation problem (and a missing golang dependency as a bonus).

Let me know if there are other pending problems for Gogs. I use it on a daily basis, but I can't test all its features and configuration options; any feedback in this regard is more than welcome.

**Comment by stikonas** [comment]
Thanks. It seems to be working on arm, so I guess ~arm can be keyworded.

Initially, I had some problem with systemd unit file but after I uncommented After mysql it worked. I wonder if this can be done automatically based on use flags.

**Comment by Dr-Terrible** [comment]
> Thanks. It seems to be working on arm, so I guess ~arm can be keyworded.

I'll add the keyword then.

> Initially, I had some problem with systemd unit file but after I uncommented After mysql it worked. I wonder if this can be done automatically based on use flags.

Sure, it could be done. I did it for another ebuild and it's not a big deal. A revision bump is coming.
