### ISSUE TITLE
Build go with buildmode=pie for Gentoo hardened

### ISSUE THREAD

**Issue by jsevilleja** [Dr-Terrible/go-overlay#52]
Some projects fail to execute on Gentoo hardened because text relocations. To solve this, go projects should be build with "-buildmode=pie".
I attach a patched golang-common.eclass.
[golang-common.eclass.txt](https://github.com/Dr-Terrible/go-overlay/files/672453/golang-common.eclass.txt)

**Comment by Dr-Terrible** [comment]
Hi @jsevilleja, thank you for the report.

> Some projects fail to execute on Gentoo hardened because text relocations

Out of curiosity, can you tell me which ebuilds failed the compilation?

> I attach a patched golang-common.eclass.

It needs to be tweaked here and there, but sounds good to me; is it OK for you if I force `-buildmode=pie` behind the USE flag `pie` so it can be properly picked up by hardened profiles?

**Comment by jsevilleja** [comment]
That would be awesome, thanks. I only use www-apps/gogs and www-apps/hugo, and I have only found the bug with gogs.
