### ISSUE TITLE
[www-apps/hugo] 0.18

### ISSUE THREAD

**Issue by jsevilleja** [Dr-Terrible/go-overlay#53]
Hugo 0.18 has been released. Can you update the ebuild, please?

**Comment by Dr-Terrible** [comment]
Hi @jsevilleja, hugo v01.8 is already packaged: https://github.com/Dr-Terrible/go-overlay/tree/master/www-apps/hugo  ;)

**Comment by jsevilleja** [comment]
My bad, thought I had an up-to-date overlay. Sorry.
