### ISSUE TITLE
Wuzz

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/go-overlay#56]
What do you think about this project? Interesting? https://github.com/asciimoo/wuzz

I am thinking about creating an ebuild for it.

**Comment by Dr-Terrible** [comment]
Hi @bpinto, LGTM.

Feel free to create an ebuild. Ask for help, if you find yourself in trouble.

**Comment by l29ah** [comment]
Is there an ebuild generator btw? All the go stuff look very similar and scriptable.

**Comment by Dr-Terrible** [comment]
I have pushed `wuzz` v0.4.0 to the overlay, in case someone is still interested.

On a side node, there is the tool [httplab](https://github.com/gchaincl/httplab/releases) which is a clone of `wuzz`, but with more features. I'm thinking of packaging `httplab` too if there is enough interest (it has vendored deps, so it should not be too hard).

**Comment by bpinto** [comment]
Interesting, I am looking for an easy way to test API requests during development... `wuzz` might not be the best tool for that, but will give it a go now!
