### ISSUE TITLE
[www-apps/hugo] 0.20.5

### ISSUE THREAD

**Issue by elbaulp** [Dr-Terrible/go-overlay#62]
Hugo has been updated to 0.20.5 (https://github.com/spf13/hugo/releases)

I am trying to make the changes necessary to update the ebuild by reading the developer's guide, but it is very extense. 

Could you give me some hints on how to update an ebuild? Maybe I could create a  PR if you do not have time to update Hugo.

Thanks and best regards.

**Comment by Dr-Terrible** [comment]
I have updated hugo to the last stable version (v0.31).
Let me know if everything is working correctly ;)
