### ISSUE TITLE
[app-shells/fzf] Dependencies

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/go-overlay#72]
I've notice we are using released versions for the fzf dependencies, but the ones defined on [glide.lock](https://github.com/junegunn/fzf/blob/master/glide.lock) are not those. Shouldn't we update them?

**Comment by Dr-Terrible** [comment]
Apparently, `github.com/gdamore/tcell` and `github.com/lucasb-eyer/go-colorful` are not used by fzf. They are part of the fzf's `ansi` subpackage, but that subpackage is not used anywhere by fzf, thus the go compiler skips it. Maybe that subpackage is just a leftover, or a new incomplete part that will be used in a future release.

Unless there are some broken fzf's features, it's safe to assume those deps are not necessary.
