### ISSUE TITLE
www-apps/hugo fails to fetch sources

### ISSUE THREAD

**Issue by fat0troll** [Dr-Terrible/go-overlay#9]
Any of hugo versions (stable and ~) failing to install because of pkg-inflect source size mismatch.

build.log for stable version: https://paste.pztrn.name/1367/
build.log for unstable version: https://paste.pztrn.name/1368/

In both logs same fail exist:

```
!!! Fetched file: bitbucket.org-pkg-inflect-8961c3750a47.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      11544
!!! Expected: 11533
```

**Comment by Dr-Terrible** [comment]
Thank you for the report @fat0troll. I'll fix it ASAP.

**Comment by Dr-Terrible** [comment]
Commit 0d55113 should have fixed the issue. Let me know if there are other problems with Hugo ebuilds.

**Comment by fat0troll** [comment]
It works! Thank you, @Dr-Terrible!
