### ISSUE TITLE
[app-crypt/certspotter] ebuild request

### ISSUE THREAD

**Issue by oskar456** [Dr-Terrible/go-overlay#93]
[Cert Spotter](https://github.com/SSLMate/certspotter) is an Certificate Transparency log monitor written in Go.

It would be nice if there were ebuilds for it.

**Comment by Dr-Terrible** [comment]
@oskar456 let me know if the package works as intended, or if there are missing components ;)

**Comment by oskar456** [comment]
Works like a charm! Thanks a lot! :1st_place_medal:
